# Author      : Sergio Romera
# Created     : 10/03/2022
# Description : Cluster1 config file

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster1
spec:
  instances: 3
  imageName: ###IMAGENAME###
  enableSuperuserAccess: true

  replicationSlots:
    highAvailability:
      enabled: true

  postgresql:

    synchronous:
      method: any
      number: 1
      # preferred: Focuses on self-healing and high availability by automatically 
      # disabling synchronous replication when no replicas are available in the cluster.
      dataDurability: preferred
  
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  storage:
    size: 1Gi
  
  backup:
    barmanObjectStore:
      destinationPath: "###S3_DESTINATIONPATH###"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
        sessionToken:
          name: aws-creds
          key: ACCESS_SESSION_TOKEN
      wal:
          compression: gzip
          encryption: AES256
      data:
        #compression: gzip
        #encryption: AES256
        immediateCheckpoint: true
        #jobs: 2
    retentionPolicy: "1d"
