# Author      : Sergio Romera
# Created     : 10/03/2022
# Description : Cluster1 config file for streaming restore

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster1
spec:
  instances: 3
  imageName: ###IMAGENAME###
  enableSuperuserAccess: true

  replicationSlots:
    highAvailability:
      enabled: true

  postgresql:

    synchronous:
      method: any
      number: 1
      # preferred: Focuses on self-healing and high availability by automatically 
      # disabling synchronous replication when no replicas are available in the cluster.
      dataDurability: preferred
  
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
  
  bootstrap:
     recovery:
       backup:
         name: backup2-test
  
  replica:
    enabled: true
    source: cluster2

  monitoring:
   enablePodMonitor: true

  storage:
    size: 1Gi
    
  externalClusters:
  - name: cluster2
    connectionParameters:
      host: cluster2-rw
      user: streaming_replica
    sslKey:
      name: cluster2-replication
      key: tls.key
    sslCert:
      name: cluster2-replication
      key: tls.crt
    sslRootCert:
      name: cluster2-ca
      key: ca.crt
    barmanObjectStore:
        destinationPath: "###S3_DESTINATIONPATH###"
        s3Credentials:
          accessKeyId:
            name: aws-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws-creds
            key: ACCESS_SECRET_KEY
          sessionToken:
            name: aws-creds
            key: ACCESS_SESSION_TOKEN
        wal:
          compression: gzip
          encryption: AES256
          maxParallel: 8
