# Author      : Sergio Romera
# Created     : 10/03/2022
# Description : Cluster2 config file to be used when cluster2 has been promoted
#               in primary cluster. This config allow you to backup cluster2 in S3.

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster2
spec:
  instances: 3
  imageName: ###IMAGENAME###
  enableSuperuserAccess: true

  replicationSlots:
    highAvailability:
      enabled: true

  postgresql:

    synchronous:
      method: any
      number: 1
      # preferred: Focuses on self-healing and high availability by automatically 
      # disabling synchronous replication when no replicas are available in the cluster.
      dataDurability: preferred
  
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  monitoring:
   enablePodMonitor: true
  
  bootstrap:
     recovery:
       backup:
         name: backup-test
  
  #replica:
  #  enabled: true
  #  source: cluster1

  storage:
    size: 1Gi
    
  backup:
    barmanObjectStore:
      destinationPath: "###S3_DESTINATIONPATH###"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
        sessionToken:
          name: aws-creds
          key: ACCESS_SESSION_TOKEN
      wal:
        compression: gzip
        encryption: AES256
        maxParallel: 8
